TAX_YEAR = 2022
TOWNSHIP_LIST = ["North Chicago", "South Chicago", "West Chicago"]

PCA_N_COMPONENTS = 10

N_CLUSTERS = 850

KMEANS_NCLUSTERS = N_CLUSTERS
KMEANS_NINIT = 25
KMEANS_MAXITER = 900

AGG_NCLUSTERS = N_CLUSTERS
AGG_METRIC = "euclidean"
AGG_COMPUTEFULLTREE = True
AGG_LINKAGE = "ward"

SKATERREG_NCLUSTERS = N_CLUSTERS
SKATERREG_FLOOR = 1
SKATERREG_ISLANDS = "increase"

OUTPUT_FILE = f"data/finished/fullcity_new_{str(N_CLUSTERS)}.gpkg"
